on:
  push:
    branches: [ggwp]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: docswebsite:latest
          outputs: type=docker,dest=/tmp/docswebsite.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docswebsite
          path: /tmp/docswebsite.tar
  use:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docswebsite
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/docswebsite.tar
          docker image ls -a
          cd /home/whes1015
          docker compose up -d