name: "deploy"

on:
  push:
    branches: main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: images.exptech.dev
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_NO_SUMMARY: true
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: images.exptech.dev/exptech-docs:latest
  use:
    runs-on: self-hosted
    needs: docker
    steps:
      - name: Load image
        run: |
          docker pull images.exptech.dev/exptech-docs
          docker image ls -a
          cd /home/whes1015
          docker compose up -d
          docker image rm $(docker images -f "dangling=true" -q)